### PR TITLE
edited filestructure

### PR DESCRIPTION
**Pull request by pablomendezroyo**
- [ ] Edit script endpoints to point to the new script locations

### CODE REVIEW

**Comment by pablomendezroyo** [comment]
tested by creating and installing dappnode ISO

**Comment by 3alpha** [comment]
Do we have to be careful with installer and prerequisites paths because we have installer.dappnode.io and prerequisites.dappnode.io redirect?

**Comment by 3alpha** [comment]
One more thing, I can comment on just moved files, but in utils/scripts there are .cfg files which are used in ISO only I think. If there is no other reason why is it there I think we should move it together with ISO stuff

**Review by dapplion — APPROVED** [review]
Look good to me can you add a note in the some section of the README towards the end about what to expect to find in each directory? Specially `utils` since it's the most generic name

**Comment by pablomendezroyo** [comment]
> One more thing, I can comment on just moved files, but in utils/scripts there are .cfg files which are used in ISO only I think. If there is no other reason why is it there I think we should move it together with ISO stuff
Done in last commit

**Comment by pablomendezroyo** [comment]
> Maybe we should move .dappnode_profile file from iso folder?

yeah make sense!

It is already in iso folder since last commit

**Comment by pablomendezroyo** [comment]
> Look good to me can you add a note in the some section of the README towards the end about what to expect to find in each directory? Specially `utils` since it's the most generic name

Done in recent commit

**Review by dapplion — APPROVED** [review]

**Pull request merged**
